on:
    push:
        branches: main

jobs:
    deploy-infra:
        runs-on: ubuntu-latest
        steps:
            - uses: checkout@4
            - uses: hashicorp/setup-terraform@v3
            - run: cd terraform
            - run: terraform init
            - run: terraform plan -out myplan
            - run: terraform apply myplan